### ISSUE TITLE
Extend returned App model with scm_url in [/apps] endpoint

### ISSUE THREAD

**Issue by kanuku** [zalando-stups/kio#22]
Right now to retrieve all the SCM-URL's from `zalando-stups/kio` we need to call 2 endpoints.
- First we call `/apps` which includes all the id's of all applications. 
- Second we call `/apps/id` for each id we got on the first call.

It would be great if zalando/kontrolletti#60 could call `/apps` endpoint once to get all registered SCM-url's in the App json-object. 
**Is it possible to extend the returned json object to include the `scm-url` and `time-created`?**

**Comment by prayerslayer** [comment]
Does this have practical implications for you or is it only convenience?

Aside from that: Since we check in fullstop for the presence of all URL fields one could consider those part of the basic data of an application. Following from there it would be reasonable to provide them along with the auditing fields (created, last_modified) in `/apps`.

**Comment by kanuku** [comment]
Yes it is more convenient, but would also lower the amount of traffic and calls made to `kio`.
`kio` returns now around 800 apps from the `/apps` endpoint. 
To get more detailed information about all 800 returned apps, [kontrolletti](https://github.com/zalando/kontrolletti) must request the detailed info separately for each of the 800 apps,  in its own http-request. 
Thank you once again for the quick reaction :+1: !
